 // Array of language-phrase pairs (replace with your own pairs)
const lingue = [
    { lingua: "Afrikaans", frase: "welkom" },
    { lingua: "Amarico", frase: "እንኳን ደህና መጣህ" },
    { lingua: "Hausa", frase: "barka da zuwa" },
    { lingua: "Igbo", frase: "nabata" },
    { lingua: "Malgascio", frase: "tonga soa" },
    { lingua: "Nyanja", frase: "takulandirani" },
    { lingua: "Shona", frase: "mauya" },
    { lingua: "Somalo", frase: "soo dhawow" },
    { lingua: "Sesotho", frase: "amohela" },
    { lingua: "Swahili", frase: "karibu" },
    { lingua: "Xhosa", frase: "wamkelekile" },
    { lingua: "Yoruba", frase: "kaabo" },
    { lingua: "Zulu", frase: "wamukelekile" },
    { lingua: "Bambara", frase: "i danse" },
    { lingua: "Pecora", frase: "woezɔ̃" },
    { lingua: "Kinyarwanda", frase: "murakaza neza" },
    { lingua: "Lingala", frase: "boyei malamu" },
    { lingua: "Uganda", frase: "kaale" },
    { lingua: "Sepedi", frase: "le amogetšwe" },
    { lingua: "Twi", frase: "akwaaba" },
    { lingua: "Arabo", frase: "أهلا بك" },
    { lingua: "Ebraico", frase: "ברוך הבא" },
    { lingua: "Pashto", frase: "ښه راغلاست" },
    { lingua: "Arabo", frase: "أهلا بك" },
    { lingua: "Albanese", frase: "mirëseardhje" },
    { lingua: "Basco", frase: "ongi etorria" },
    { lingua: "Catalano", frase: "benvingut" },
    { lingua: "Croato", frase: "dobrodošli" },
    { lingua: "Danese", frase: "velkommen" },
    { lingua: "Olandese", frase: "welkom" },
    { lingua: "Inglese", frase: "welcome" },
    { lingua: "Francese", frase: "bienvenue" },
    { lingua: "Frisone", frase: "wolkom" },
    { lingua: "Galiziano", frase: "benvido" },
    { lingua: "Tedesco", frase: "herzlich willkommen" },
    { lingua: "Islandese", frase: "velkominn" },
    { lingua: "Irlandesi", frase: "fáilte" },
    { lingua: "Italiano", frase: "benvenuto" },
    { lingua: "Lussemburghese", frase: "wëllkomm" },
    { lingua: "Maltese", frase: "merħba" },
    { lingua: "Norvegese", frase: "velkommen" },
    { lingua: "Portoghese", frase: "bem-vinda" },
    { lingua: "Gaelico", frase: "fàilte" },
    { lingua: "Spagnolo", frase: "bienvenidos" },
    { lingua: "Svedese", frase: "välkommen" },
    { lingua: "Gallese", frase: "croeso" },
    { lingua: "Bielorusso", frase: "вітаем" },
    { lingua: "Bosniaco", frase: "dobrodošli" },
    { lingua: "Bulgaro", frase: "добре дошли" },
    { lingua: "Ceco", frase: "vítejte" },
    { lingua: "Estone", frase: "tere tulemast" },
    { lingua: "Finlandese", frase: "tervetuloa" },
    { lingua: "Ungherese", frase: "üdvözöljük" },
    { lingua: "Lettone", frase: "laipni gaidīti" },
    { lingua: "Lituano", frase: "sveiki" },
    { lingua: "Macedone", frase: "добредојде" },
    { lingua: "Polacco", frase: "witamy" },
    { lingua: "Rumeno", frase: "bine ati venit" },
    { lingua: "Russo", frase: "добро пожаловать" },
    { lingua: "Serbo", frase: "добродошли" },
    { lingua: "Slovacco", frase: "vitaj" },
    { lingua: "Sloveno", frase: "dobrodošli" },
    { lingua: "Ucraino", frase: "ласкаво просимо" },
    { lingua: "Bengalese", frase: "স্বাগত" },
    { lingua: "Gujarati", frase: "સ્વાગત છે" },
    { lingua: "Hindi", frase: "स्वागत हे" },
    { lingua: "Kannada", frase: "ಸ್ವಾಗತ" },
    { lingua: "Malayalam", frase: "സ്വാഗതം" },
    { lingua: "Marathi", frase: "स्वागत आहे" },
    { lingua: "Nepalese", frase: "स्वागतम्" },
    { lingua: "Punjabi", frase: "ਸਵਾਗਤ ਹੈ" },
    { lingua: "Singalese", frase: "සාදරයෙන් පිළිගනිමු" },
    { lingua: "Tamil", frase: "வரவேற்பு" },
    { lingua: "Telugu", frase: "స్వాగతం" },
    { lingua: "Urdu", frase: "خوش آمدید" },
    { lingua: "Cinese", frase: "欢迎" },
    { lingua: "Cinese", frase: "歡迎" },
    { lingua: "Giapponese", frase: "ようこそ" },
    { lingua: "Coreano", frase: "어서 오십시오" },
    { lingua: "Mongolo", frase: "тавтай морилно уу" },
    { lingua: "Myanmar", frase: "ကြိုဆိုပါတယ်" },
    { lingua: "Indonesiano", frase: "selamat datang" },
    { lingua: "Giavanese", frase: "sugeng rawuh" },
    { lingua: "Khmer", frase: "សូមស្វាគមន៍" },
    { lingua: "Lao", frase: "ຍິນດີຕ້ອນຮັບ" },
    { lingua: "Malese", frase: "selamat datang" },
    { lingua: "Tailandese", frase: "ยินดีต้อนรับ" },
    { lingua: "Vietnamita", frase: "chào mừng" },
    { lingua: "Filippino", frase: "maligayang pagdating" },
    { lingua: "Azero", frase: "xoş gəlmisiniz" },
    { lingua: "Kazako", frase: "қош келдіңіз" },
    { lingua: "Kirghizistan", frase: "кош келдиңиз" },
    { lingua: "Tagiko", frase: "хуш омадед" },
    { lingua: "Turkmeno", frase: "hoş geldiňiz" },
    { lingua: "Uzbeko", frase: "xush kelibsiz" },
    { lingua: "Uiguro", frase: "قارشى ئالىمىز" },
    { lingua: "Hawaiano", frase: "welina" },
    { lingua: "Maori", frase: "nau mai" },
    { lingua: "Samoano", frase: "afio mai" },
    { lingua: "Tagalog", frase: "maligayang pagdating" },
    { lingua: "Aymara", frase: "aski jutäwi" },
    { lingua: "Guarani", frase: "tapeg̃uahẽporãite" },
    { lingua: "Esperanto", frase: "bonvenon" },
    { lingua: "Latino", frase: "gratissimum" },
    { lingua: "Greco", frase: "καλως ηρθατε" },
    { lingua: "Hmong", frase: "txais tos" },
    { lingua: "Curdo", frase: "bi xêr hatî" },
    { lingua: "Turco", frase: "hoşgeldiniz" },
    { lingua: "Xhosa", frase: "wamkelekile" },
    { lingua: "Yiddish", frase: "באַגריסן" },
    { lingua: "Zulu", frase: "wamukelekile" },
    { lingua: "Assamese", frase: "স্বাগতম" },
    { lingua: "Aymara", frase: "aski jutäwi" },
    { lingua: "Bhojpuri", frase: "स्वागत" },
    { lingua: "Dhivehi", frase: "މަރުޙަބާ" },
    { lingua: "Dogri", frase: "सुआगत" },
    { lingua: "Filippino", frase: "maligayang pagdating" },
    { lingua: "Guarani", frase: "tapeg̃uahẽporãite" },
    { lingua: "Ilocano", frase: "naragsak nga isasangbay" },
    { lingua: "Krio", frase: "wɛlkɔm" },
    { lingua: "Curdo", frase: "بەخێربێیت" },
    { lingua: "Maithili", frase: "स्वागत    " },
    { lingua: "Mizo", frase: "chibai" },
    { lingua: "Oromo", frase: "baga nagaan dhufte" },
    { lingua: "Odia", frase: "ସ୍ୱାଗତ" },
    { lingua: "Quechua", frase: "allinlla chayaykamuy" },
    { lingua: "Sanscrito", frase: "स्वागतम्" },
    { lingua: "Tartaro", frase: "рәхим итегез" },
    { lingua: "Tigrino", frase: "እንኳዕ ደሓን መፁ" },
    { lingua: "Tsonga", frase: "amukela" },
    { lingua: "stop", frase: "stop" }
];

function cambiaFrase() {
  // Select a random language-phrase pair
  const indice = indexLanguage;
  const fraseRandom = lingue[indice];

  // Update the text of the h1 element
  const titolo = document.getElementById("titolo");
  titolo.textContent = fraseRandom.frase;

  // Increment the index and check if it's beyond the array length
  indexLanguage++;
  if (indexLanguage >= lingue.length) {
    clearInterval(intervalId); // Stop the interval
    titolo.textContent = "benvenuto"; // Reset the text
  }
}

var indexLanguage = 0;

// Initialize the interval ID
let intervalId = setInterval(cambiaFrase, 200);